name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          username: yuuki1967
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: yuuki1967/publish_package_training/game
          tag_with_sha: false
